version: '2.1'

services:
  backend:
    build:
      context: .
    ports:
    - "8080:8080"
    depends_on:
      - db

  db:
    image: library/postgres:alpine
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_PASSWORD: S@ng29031998
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:5050"
    restart: always
