version: '3'

services:
  backend:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - db
    restart: always
    networks:
      - sm_network

  db:
    image: library/postgres:alpine
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_PASSWORD: S@ng29031998
      POSTGRES_DB: selling-management
    ports:
      - "5432:5432"
    networks:
      - sm_network

networks:
  sm_network:
    driver: bridge