version: '2.1'

services:
  backend:
    build:
      context: .
    ports:
    - "8080:8080"
    depends_on:
      - db

  db:
    image: library/postgres:alpine
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: smu
      POSTGRES_PASSWORD: S@ng29031998
      POSTGRES_DB: selling-management
    ports:
      - "5432:5432"
